# Generated by Django 4.2.5 on 2024-02-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBADataGenius', '0002_commonplayerinfo_draftcombinestats_drafthistory_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
